

# Build
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Etapa desarrollo
FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

# Etapa producción
FROM base AS build
RUN npm run build

FROM nginx:1.28-alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


